#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;

// load
require_once __DIR__ . '/bootstrap/autoload.php';

// new
$application = new Application();

// 同步cmdb命令
$application->add(new Slug\SomeCommand());

// run
$application->run();
